#!/bin/bash
for num in {1..10..2}
do
 echo "Number: $num"
done

-----------------------------------------
While test

#!/bin/bash

num=5

while (( num <= 10 )) 
do
        echo $num
        (( num = num + 1 )) 
done